//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancielCrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankProccess
    {
        public int BankProccessId { get; set; }
        public string BankDescription { get; set; }
        public Nullable<System.DateTime> ProccessDate { get; set; }
        public string ProccessType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int BankId { get; set; }
        public int UserId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual User User { get; set; }
    }
}
